import type { EpisodeSeed, SeriesSeed, SeriesSlug } from "./types";

/**
 * Catálogo TVI BOX — as 8 séries do protótipo (títulos e posters fictícios,
 * atores gerados por IA). Fonte de verdade para o seed da base de dados.
 */
export const SERIES: SeriesSeed[] = [
  {
    slug: "sangue",
    title: "Sangue & Herança",
    genre: "Vingança",
    tagline: "TVI Box original",
    synopsis:
      "Na noite do velório do avô, Beatriz descobre um segundo testamento escondido no cofre do palácio de Sintra. Tudo o que o irmão lhe contou era mentira — e a família Sequeira está prestes a rasgar-se ao meio.",
    badge: "hot",
    palette: { from: "#7a0d14", to: "#2a0508" },
    totalEpisodes: 40,
    sortOrder: 1,
    stats: { likes: 14200, comments: 892 },
  },
  {
    slug: "patroa",
    title: "A Patroa",
    genre: "Romance · CEO",
    tagline: "Novo",
    synopsis:
      "Helena Vasconcelos é a CEO mais temida de Lisboa. O novo motorista que acabou de contratar tem um segredo: veio para a destruir. Ela também tem um: já sabe quem ele é.",
    badge: "new",
    palette: { from: "#0d2340", to: "#05080f" },
    totalEpisodes: 36,
    sortOrder: 2,
    stats: { likes: 9800, comments: 511 },
  },
  {
    slug: "traicao",
    title: "Traição em Sintra",
    genre: "Drama",
    tagline: "Tendência",
    synopsis:
      "Às três da manhã, Marta atende o telemóvel do marido. A voz do outro lado conhece-a pelo nome — e sabe exatamente o que está no porta-luvas do carro dele.",
    palette: { from: "#3a0a2e", to: "#0c0410" },
    totalEpisodes: 48,
    sortOrder: 3,
    stats: { likes: 21500, comments: 1300 },
  },
  {
    slug: "regresso",
    title: "O Regresso",
    genre: "Mistério",
    tagline: "",
    synopsis:
      "Quinze anos depois do próprio funeral, Duarte volta à aldeia transmontana onde toda a gente o enterrou. A mãe chora, o inspetor cala-se — e o irmão ainda vive na mesma casa.",
    palette: { from: "#143a2c", to: "#04100b" },
    totalEpisodes: 30,
    sortOrder: 4,
    stats: { likes: 6400, comments: 377 },
  },
  {
    slug: "verao",
    title: "Amor de Verão",
    genre: "Romance",
    tagline: "",
    synopsis:
      "Na última noite de agosto, Inês tem de escolher entre o comboio para Lisboa e o surfista que a fez esquecer o noivo. O problema é que os dois homens partilham mais do que ela imagina.",
    palette: { from: "#a8551a", to: "#2a0f04" },
    totalEpisodes: 24,
    sortOrder: 5,
    stats: { likes: 8100, comments: 462 },
  },
  {
    slug: "divida",
    title: "Dívida de Família",
    genre: "Suspense",
    tagline: "",
    synopsis:
      "Ao jantar de família chega um envelope sem remetente. Dentro, uma fotografia e um prazo: 48 horas. Teresa tem de descobrir quem, à mesa, a está a chantagear.",
    badge: "hot",
    palette: { from: "#1a1a2e", to: "#05050d" },
    totalEpisodes: 52,
    sortOrder: 6,
    stats: { likes: 7100, comments: 430 },
  },
  {
    slug: "fogo",
    title: "Fogo Cruzado",
    genre: "Ação",
    tagline: "Novo",
    synopsis:
      "A inspetora Sofia Rocha resgata um informador num armazém de Marvila. Só duas pessoas sabiam a hora e o sítio — e uma delas é o seu parceiro.",
    badge: "new",
    palette: { from: "#8e1a05", to: "#1a0502" },
    totalEpisodes: 28,
    sortOrder: 7,
    stats: { likes: 5300, comments: 298 },
  },
  {
    slug: "promessa",
    title: "A Promessa",
    genre: "Época",
    tagline: "",
    synopsis:
      "Lisboa, 1943. Numa cidade cheia de espiões e refugiados, Amélia promete ao pai casar com um alemão — e promete a um jornalista fugir num barco que parte no mesmo sábado.",
    palette: { from: "#2d1a4d", to: "#0a0514" },
    totalEpisodes: 40,
    sortOrder: 8,
    stats: { likes: 6900, comments: 351 },
  },
];

export const SERIES_BY_SLUG: Record<SeriesSlug, SeriesSeed> = Object.fromEntries(
  SERIES.map((s) => [s.slug, s])
) as Record<SeriesSlug, SeriesSeed>;

/**
 * Episódios do lançamento: EP1 grátis e produzido; EP2 atrás do paywall
 * (cliffhanger), a produzir pelo pipeline Veo.
 */
export const EPISODES: EpisodeSeed[] = [
  {
    series: "sangue",
    number: 1,
    title: "O segundo testamento",
    synopsis:
      "Beatriz encontra o segundo testamento escondido no cofre do avô. Tudo o que o irmão lhe contou era mentira.",
    hookTitle: "O terceiro envelope",
    hookText: "O notário traz um terceiro testamento — e nenhum dos irmãos vai gostar do que lá está.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "sangue",
    number: 2,
    title: "O terceiro envelope",
    synopsis:
      "O notário lê o terceiro testamento: o palácio fica para uma filha que ninguém conhecia — e que vive naquela casa há trinta anos.",
    hookTitle: "O terceiro envelope",
    hookText: "O notário lê o terceiro testamento. A herdeira vive no palácio há trinta anos — e ninguém reparou.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "sangue",
    number: 3,
    title: "A filha do patriarca",
    synopsis: "Dona Graça tem a prova de que é filha de Augusto Sequeira. Rodrigo tem um plano para a fazer desaparecer.",
    hookTitle: "A filha do patriarca",
    hookText: "Graça tem a prova. Rodrigo tem um plano para a fazer desaparecer antes das dez da manhã.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "patroa",
    number: 1,
    title: "O novo motorista",
    synopsis:
      "A CEO mais temida de Lisboa não sabe que o homem que acabou de contratar veio para a destruir. Ou sabe?",
    hookTitle: "Sete da manhã",
    hookText: "Helena manda Tiago buscá-la a um sítio que ele conhece demasiado bem: a antiga fábrica de Setúbal.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "patroa",
    number: 2,
    title: "Sete da manhã",
    synopsis: "Helena leva Tiago à fábrica de Setúbal onde o pai dele morreu — e entrega-lhe o relatório verdadeiro do acidente.",
    hookTitle: "Sete da manhã",
    hookText: "Helena leva Tiago à fábrica onde o pai dele morreu. O relatório verdadeiro do acidente está no bolso dela.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "patroa",
    number: 3,
    title: "Quem o empurrou",
    synopsis: "O homem que empurrou o pai de Tiago acaba de chegar à fábrica. Helena conhece-o há dez anos.",
    hookTitle: "Quem o empurrou",
    hookText: "O homem que empurrou o pai de Tiago está à porta da fábrica. Helena conhece-o há dez anos — e ele sabe que ela falou.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "traicao",
    number: 1,
    title: "A chamada às 3 da manhã",
    synopsis: "Marta atende o telemóvel do marido. A voz do outro lado conhece-a pelo nome.",
    hookTitle: "Quarto 214",
    hookText: "Marta vai ao Hotel Palácio com o cartão que encontrou. Alguém a espera no quarto 214.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "traicao",
    number: 2,
    title: "Quarto 214",
    synopsis: "Marta usa o cartão do hotel. Alguém a espera lá dentro.",
    hookTitle: "Quarto 214",
    hookText: "Marta vai ao Hotel Palácio com o cartão que encontrou. Alguém a espera no quarto 214.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "regresso",
    number: 1,
    title: "Quinze anos depois",
    synopsis: "Um homem desce do autocarro e vai visitar a própria campa. A aldeia inteira enterrou-o em 2011.",
    hookTitle: "O irmão",
    hookText: "O irmão de Duarte desce as escadas. Quinze anos de silêncio acabam esta noite.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "regresso",
    number: 2,
    title: "O irmão",
    synopsis: "Os dois irmãos frente a frente pela primeira vez desde o funeral.",
    hookTitle: "O irmão",
    hookText: "O irmão de Duarte desce as escadas. Quinze anos de silêncio acabam esta noite.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "verao",
    number: 1,
    title: "A última noite de agosto",
    synopsis: "Inês tem onze horas até ao comboio para Lisboa. Miguel quer que fique. O noivo dela acabou de chegar.",
    hookTitle: "Dois irmãos, uma praia",
    hookText: "Ricardo desce até à areia. Miguel não sai da frente de Inês. E Carla sabe mais do que diz.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "verao",
    number: 2,
    title: "Dois irmãos, uma praia",
    synopsis: "Ricardo e Miguel frente a frente na areia. Inês tem de escolher agora.",
    hookTitle: "Dois irmãos, uma praia",
    hookText: "Ricardo desce até à areia. Miguel não sai da frente de Inês. E Carla sabe mais do que diz.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "divida",
    number: 1,
    title: "O envelope sem remetente",
    synopsis: "Dentro do envelope, uma única fotografia. E um prazo: 48 horas.",
    hookTitle: "A sogra sabia",
    hookText: "Dona Isabel confessa que tirou a fotografia. Mas não foi ela que a enviou.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "divida",
    number: 2,
    title: "A sogra sabia",
    synopsis: "Dona Isabel tirou a fotografia. Mas quem a enviou está ainda mais perto.",
    hookTitle: "A sogra sabia",
    hookText: "Dona Isabel confessa que tirou a fotografia. Mas não foi ela que a enviou.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "fogo",
    number: 1,
    title: "O informador",
    synopsis: "Sofia resgata o informador num armazém de Marvila. Só duas pessoas sabiam a hora e o sítio.",
    hookTitle: "O nome",
    hookText: "Rui, ferido, diz o nome de quem os traiu. Sofia conhece-o desde a academia.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "fogo",
    number: 2,
    title: "O nome",
    synopsis: "Rui diz o nome do traidor. Sofia conhece-o desde a academia.",
    hookTitle: "O nome",
    hookText: "Rui, ferido, diz o nome de quem os traiu. Sofia conhece-o desde a academia.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
  {
    series: "promessa",
    number: 1,
    title: "Lisboa, 1943",
    synopsis: "Frederico pede Amélia em casamento no café do Rossio. O preço da lista de refugiados é ela própria.",
    hookTitle: "Cais de Alcântara",
    hookText: "O barco parte sábado às seis. Frederico está preso pela PVDE. Amélia tem de decidir sozinha.",
    isFree: true,
    coinCost: 0,
    status: "published",
  },
  {
    series: "promessa",
    number: 2,
    title: "Cais de Alcântara",
    synopsis: "O barco parte sábado às seis. Amélia tem de decidir sozinha.",
    hookTitle: "Cais de Alcântara",
    hookText: "O barco parte sábado às seis. Frederico está preso pela PVDE. Amélia tem de decidir sozinha.",
    isFree: false,
    coinCost: 15,
    status: "coming_soon",
  },
];
